name             'gitlab'
maintainer       'Zühlke Engineering GmbH'
maintainer_email 'bvo@zuehlke.com'
license          'All rights reserved'
description      'Installs/Configures gitlab'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'apt','2.0.0'
depends          'rvm','0.9.0'
depends          'mysql'
depends          'database'
depends          'vagrant-ohai'